In [1]:
import numpy as np

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.arange(2,100,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [7]:
np.ones(5)*10

array([10., 10., 10., 10., 10.])

In [9]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.random.rand()*5

1.0357298906151473

In [14]:
np.random.randn(25).reshape(5,5)

array([[-0.91682938,  0.03796317,  0.03862884,  1.86111257, -0.24915602],
       [-0.73206704,  0.73298568, -0.78081665, -0.18770487, -0.56162106],
       [ 0.75426741,  0.24099613, -0.28809804, -1.11339908, -0.74994067],
       [-1.03998336,  0.09567726, -0.51728219,  1.02912219, -0.49671932],
       [ 0.31140804,  1.23688422, -1.69660385, -1.1516537 ,  0.17538487]])

In [15]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [16]:
arr = np.arange(1,101).reshape(10,10)

In [17]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [18]:
arr[4:]

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [20]:
arr[6:,4:]

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [26]:
arr[:3,2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [29]:
arr[:3,1]

array([ 2, 12, 22])

In [30]:
arr[:,9]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [31]:
arr1 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)
arr2 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)

In [32]:
arr1 +arr2

array([[3, 2, 3],
       [4, 1, 3],
       [3, 5, 6]])