In [1]:
import numpy as np

In [2]:
arr = np.arange(1,25)

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [4]:
arr[1]

2

In [5]:
arr[1:7]

array([2, 3, 4, 5, 6, 7])

In [6]:
arr[1:4:5]

array([2])

In [7]:
arr[:4]

array([1, 2, 3, 4])

In [8]:
arr[::3]

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [9]:
arr[5] = 25
arr

array([ 1,  2,  3,  4,  5, 25,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [10]:
arr[::3] =24

In [11]:
arr

array([24,  2,  3, 24,  5, 25, 24,  8,  9, 24, 11, 12, 24, 14, 15, 24, 17,
       18, 24, 20, 21, 24, 23, 24])

In [12]:
arr2 = np.arange(1,10)

In [13]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr2 = arr

In [15]:
arr2

array([24,  2,  3, 24,  5, 25, 24,  8,  9, 24, 11, 12, 24, 14, 15, 24, 17,
       18, 24, 20, 21, 24, 23, 24])

In [16]:
arr2[::3] =100

In [17]:
arr

array([100,   2,   3, 100,   5,  25, 100,   8,   9, 100,  11,  12, 100,
        14,  15, 100,  17,  18, 100,  20,  21, 100,  23,  24])

In [18]:
#arr2 de meydana gelen bir değişim arr2 yi etkiler.

In [20]:
arr3 = np.arange(1,10)

In [21]:
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr = arr2.copy()

In [23]:
arr

array([100,   2,   3, 100,   5,  25, 100,   8,   9, 100,  11,  12, 100,
        14,  15, 100,  17,  18, 100,  20,  21, 100,  23,  24])

In [24]:
#bu şekilde arr değiştiğinde arr2 değişmeyecek.

In [32]:
newarray = np.arange(1,31)

In [33]:
newarray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [34]:
newarray.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [35]:
newarray = newarray.reshape(5,6)

In [36]:
newarray

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [37]:
newarray[0,1]

2

In [38]:
#tüm satırların sadece ilk 3 değerini almak istersek = 
newarray[:,:3]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [39]:
newarray[:3,:3]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15]])

In [40]:
#ilk 3 satırı al onların içindende ilk 3 sütünü al demiş olduk

In [41]:
newarray[:2,:]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [42]:
#sadece ilk 2 satırı ve komple al 

In [43]:
newarray[:2]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [44]:
#Array Filtreleme = 
arr = np.arange(1,10)

In [45]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True])

In [49]:
boolean_array = arr >4

In [50]:
arr[boolean_array]

array([5, 6, 7, 8, 9])

In [52]:
arr[arr>5]#2.bir fitreleme tekniği 

array([6, 7, 8, 9])