In [1]:
#bir liste oluşturalım :
data_list = [1,2,3,4]
#bu tek boyutlu bir listedir.
data_list

[1, 2, 3, 4]

In [2]:
#bu yapıyı numpy arrayi ilede oluşturabiliriz.
import numpy as np
#genel olarak kullanımı np'dir.np üzerinden bunu kullanalım şeklinde...
arr = np.array(data_list)

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
#çok boyultu array = 
data_list2 = [[50,60,70],[8,58,85],[855,588,858]]
arr2 =np.array(data_list2)


In [5]:
arr2

array([[ 50,  60,  70],
       [  8,  58,  85],
       [855, 588, 858]])

In [6]:
#önceden liste oluşturmak gibi bir zorunluluğumuz yok değerleri array oluştururkende verebiliriz.
arr3 = np.array([0,1,2,3,4,5,6,7,8,9,10])
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#istedğimiz indexte bulunan elemanı listelerden aldığımız gib alarabiliriz.
arr3[2]

2

In [8]:
arr2[2,2]

858

In [10]:
#arraylerde arr2[2][1] yerine üstte kullanıdğımz yapıyı kullanıyoruz.
arr2[1][2]
#bu yöntemde mevcut lakin ratik değil

85

In [12]:
#listelerde kullandığımız range gibi burada da arange methodumuz bulunuyor.
np.arange(50,60)

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [13]:
np.arange(0,100,5)#0 dan 100 e 5 er 5 er atlayarak yazıyoruz.

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [14]:
np.zeros(175)#yapının içine kaç yazarsanız yapınızın içerisinde o kadar 0 olacaktır.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])

In [15]:
np.ones(58)#58 adet bir elemanımız olacak

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [16]:
#burada 1 ve 0 ların yanında bulunan noktalar numpy çalışma şeklinden kaynaklı bu integer değerleri floata dönüştürerek depoluyor.
#zeros ve onse ile çok boyutlu matrisler(arrayler oluşturabiliriz.)
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
#linspace() içerisine yazdığınız aralıkları yine belirtmiş olduğunuz kadar eşit parçaya bölerek belirttiğiniz adet de veri saklayan bir yapı.
np.linspace(0,150,7)

array([  0.,  25.,  50.,  75., 100., 125., 150.])

In [22]:
np.linspace(0,1,8)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

In [24]:
np.eye(9)#9*9luk bir birim matris sonucu alırız.

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.random.randint(0,58)#0 dahil 58 değil bize rastgele bir değer dönecek

11

In [27]:
np.random.randint(0,58)

6

In [29]:
np.random.randint(588)

114

In [32]:
np.random.randint(0,58,5)#0dan 58 e kadar 5 adet random değer döndür.58 dahil değil.

array([ 8, 16,  2, 54, 45])

In [34]:
np.random.rand(9)#0 1 arasında 9 rastgele değerimiz oluşmuş oldu.

array([0.57628435, 0.60775604, 0.40188415, 0.50679629, 0.2139752 ,
       0.55255509, 0.40227803, 0.75477861, 0.57170761])

In [36]:
np.random.randn(5)#burada - değerlerimizde oluşuyor.

array([-1.1933114 ,  0.66891956, -0.11432816, -0.73307753,  0.48208407])

In [40]:
arr = np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [42]:
arr.reshape(6,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [43]:
newarray = np.random.randint(1,100,10)
newarray

array([41, 42, 97, 21, 42, 83, 20, 90, 41, 95])

In [44]:
newarray.max()#en büyük değeri getir.

97

In [45]:
newarray.min()#en küçük değer

20

In [46]:
newarray.sum()#tüm değerlerin toplamını ver

572

In [47]:
newarray.mean()#ortalama

57.2

In [48]:
newarray.argmax()#maximum sayının olduğu indexi ver

2

In [49]:
newarray.argmin()#en küçük sayının indexini ver

6

In [50]:
detarray = np.random.randint(1,150,25)

In [51]:
detarray

array([142,  34,  22, 145, 145, 125,  69, 143, 103,  41, 103,  46,  11,
        68,  78,  20, 133, 131,  47,  19,  96,  40,  40, 127,  71])

In [52]:
detarray = detarray.reshape(5,5)

In [53]:
detarray

array([[142,  34,  22, 145, 145],
       [125,  69, 143, 103,  41],
       [103,  46,  11,  68,  78],
       [ 20, 133, 131,  47,  19],
       [ 96,  40,  40, 127,  71]])

In [54]:
np.linalg.det(detarray)

3843839260.000009

In [56]:
detarray2 = np.array([[58,85],[55,88]])

In [57]:
detarray2

array([[58, 85],
       [55, 88]])

In [58]:
np.linalg.det(detarray2)

428.9999999999996

In [59]:
round(np.linalg.det(detarray2))

429.0