In [1]:
import numpy as np 


In [2]:
arr1 = np.array([50,60,70,80,90,100])
arr2 =np.array([55,58,85,88,588,855])
arr1 +arr2

array([105, 118, 155, 168, 678, 955])

In [3]:
arr1-arr2

array([  -5,    2,  -15,   -8, -498, -755])

In [4]:
arr1*arr2

array([ 2750,  3480,  5950,  7040, 52920, 85500])

In [5]:
arr1+15

array([ 65,  75,  85,  95, 105, 115])

In [6]:
arr1

array([ 50,  60,  70,  80,  90, 100])

In [7]:
arr1*58

array([2900, 3480, 4060, 4640, 5220, 5800])

In [8]:
arr1/2

array([25., 30., 35., 40., 45., 50.])

In [9]:
np.sqrt(arr1)#her bir elemanın karekökünü alıyoruz.

array([ 7.07106781,  7.74596669,  8.36660027,  8.94427191,  9.48683298,
       10.        ])